# For testing when running the microservices from Docker images,
# behind the nginx reverse proxy.
micronaut.http.services.todo.url=http://localhost:8080
micronaut.http.services.todo.path=/todo
micronaut.http.services.editcounts.url=http://localhost:8080
micronaut.http.services.editcounts.path=/edits
