# We need context paths in each Swagger UI in order for
# them to render and work correctly.
map $request_uri $redirect {
    ~/todo/swagger-ui/?$  /todo/swagger-ui?contextPath=/todo;
    ~/edits/swagger-ui/?$ /edits/swagger-ui?contextPath=/edits;
}

server {
    listen 8080;
    listen [::]:8080;
    server_name localhost;

    if ($redirect) {
        return 302 $redirect;
    }
    location /todo/ {
        proxy_pass http://todo:8080/;
    }
    location /edits/ {
        proxy_pass http://editcounts:8081/;
    }
}
